---
# handlers file for filebeat
- name: "Restart Filebeat Linux"
  service:
    name: "{{ filebeat_service }}"
    state: "restarted"

- name: "Restart Filebeat Windows"
  win_service:
    name: "{{ filebeat_service }}"
    state: "restarted"
